packages:
  - playground
catalogs:
  dev:
    '@antfu/eslint-config': ^6.7.3
    '@antfu/ni': ^27.0.1
    '@antfu/utils': ^9.3.0
    '@iconify/json': ^2.2.436
    '@types/codemirror': ^5.60.17
    '@types/node': ^24.10.11
    '@unocss/eslint-config': ^66.6.0
    '@unocss/eslint-plugin': ^66.6.0
    '@vitejs/devtools': ^0.0.0-alpha.26
    '@vitejs/plugin-vue': ^6.0.4
    '@vue/compiler-sfc': ^3.5.27
    bumpp: ^10.4.1
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    premove: ^4.0.0
    serve: ^14.2.5
    simple-git-hooks: ^2.13.1
    typescript: ^5.9.3
    unbuild: ^3.6.1
    unocss: ^66.6.0
    unplugin-auto-import: ^20.3.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-router: ^0.17.2
    vite: ^7.3.1
    vue-tsc: ^3.2.4
  frontend:
    '@vueuse/core': ^14.2.0
    '@vueuse/router': ^14.2.0
    codemirror: ^5.65.16
    codemirror-theme-vars: ^0.1.2
    comlink: ^4.4.2
    diff-match-patch-es: ^1.0.1
    echarts: ^6.0.0
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    ohash: ^2.0.11
    pathe: ^2.0.3
    perfect-debounce: ^2.1.0
    pinia: ^3.0.4
    splitpanes: ^4.0.4
    vis-data: ^8.0.3
    vis-network: ^10.0.2
    vue: ^3.5.27
    vue-echarts: ^8.0.1
    vue-router: ^4.6.4
  prod:
    '@nuxt/kit': ^4.3.0
    '@vitejs/devtools-kit': ^0.0.0-alpha.26
    ansis: ^4.2.0
    error-stack-parser-es: ^1.0.5
    obug: ^2.1.1
    open: ^11.0.0
    sirv: ^3.0.2
    unplugin-utils: ^0.3.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
catalog:
  skills-npm: ^0.1.0
