ignoreWorkspaceRootCheck: true
minimumReleaseAge: 0
minimumReleaseAgeExcludePrune: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - tinyexec

update:
  ignoreDeps:
    - typescript@7

strictPeerDependencies: false
shamefullyHoist: true
shellEmulator: true
sideEffectsCache: false

packages:
  - playground

allowBuilds:
  simple-git-hooks: true

catalogs:
  dev:
    '@antfu/eslint-config': ^9.5.1
    '@antfu/ni': ^30.6.0
    '@antfu/utils': ^9.3.0
    '@iconify/json': ^2.2.541
    '@playwright/test': ^1.64.0
    '@types/codemirror': ^5.60.18
    '@types/node': ^26.6.4
    '@unocss/eslint-config': ^66.10.5
    '@unocss/eslint-plugin': ^66.10.5
    '@unocss/reset': ^66.10.5
    '@vitejs/devtools': ^0.7.6
    '@vitejs/plugin-vue': ^6.0.9
    '@vue/compiler-sfc': ^3.5.43
    bumpp: ^12.3.0
    devframe: ^1.2.3
    eslint: ^10.12.0
    nano-staged: ^1.0.2
    premove: ^4.0.0
    publint: ^0.3.25
    serve: ^14.2.6
    simple-git-hooks: ^2.14.0
    skills-npm: ^4.0.0
    tsdown: ^0.23.0
    typescript: ^6.0.3
    unocss: ^66.10.5
    unplugin-auto-import: ^21.1.0
    unplugin-vue-components: ^32.1.0
    vite: ^8.3.4
    vitest: ^5.0.3
    vue-tsc: ^3.3.12
  frontend:
    '@vueuse/core': ^15.0.0
    '@vueuse/router': ^15.0.0
    codemirror: ^5.65.16
    codemirror-theme-vars: ^0.1.2
    comlink: ^4.4.2
    diff-match-patch-es: ^2.0.1
    echarts: ^6.1.0
    floating-vue: ^5.4.0
    fuse.js: ^7.5.0
    ohash: ^2.0.12
    pathe: ^2.0.3
    perfect-debounce: ^2.1.0
    pinia: ^4.0.3
    splitpanes: ^4.1.2
    vis-data: ^8.0.5
    vis-network: ^10.1.2
    vue: ^3.5.43
    vue-echarts: ^8.3.1
    vue-router: ^5.4.0
  prod:
    '@nuxt/kit': ^4.6.0
    '@vitejs/devtools-kit': ^0.7.6
    ansis: ^4.4.0
    error-stack-parser-es: ^2.0.1
    obug: ^3.0.0
    open: ^11.0.4
    sirv: ^3.0.2
    unplugin-utils: ^0.3.2
