packages:
  - playground
catalogs:
  dev:
    '@antfu/eslint-config': ^5.2.1
    '@antfu/ni': ^25.0.0
    '@antfu/utils': ^9.2.0
    '@iconify/json': ^2.2.377
    '@types/codemirror': ^5.60.16
    '@types/debug': ^4.1.12
    '@types/node': ^24.3.0
    '@unocss/eslint-config': ^66.4.2
    '@unocss/eslint-plugin': ^66.4.2
    '@vitejs/plugin-vue': ^6.0.1
    '@vue/compiler-sfc': ^3.5.19
    bumpp: ^10.2.3
    eslint: ^9.34.0
    lint-staged: ^16.1.5
    rimraf: ^6.0.1
    serve: ^14.2.4
    simple-git-hooks: ^2.13.1
    typescript: ^5.9.2
    unbuild: ^3.6.1
    unocss: ^66.4.2
    unplugin-auto-import: ^20.0.0
    unplugin-vue-components: ^29.0.0
    unplugin-vue-router: ^0.15.0
    vite: ^6.3.0
    vue-tsc: ^3.0.6
  frontend:
    '@vueuse/core': ^13.7.0
    '@vueuse/router': ^13.7.0
    codemirror: ^5.65.16
    codemirror-theme-vars: ^0.1.2
    comlink: ^4.4.2
    diff-match-patch-es: ^1.0.1
    echarts: ^5.6.0
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    ohash: ^2.0.11
    pathe: ^2.0.3
    perfect-debounce: ^2.0.0
    pinia: ^3.0.3
    splitpanes: ^4.0.4
    vis-data: ^8.0.1
    vis-network: ^10.0.1
    vite-dev-rpc: ^1.1.0
    vite-hot-client: ^2.1.0
    vue: ^3.5.19
    vue-echarts: ^7.0.3
    vue-router: ^4.5.1
  prod:
    '@nuxt/kit': ^4.0.3
    ansis: ^4.1.0
    debug: ^4.4.1
    error-stack-parser-es: ^1.0.5
    open: ^10.2.0
    sirv: ^3.0.1
    unplugin-utils: ^0.3.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
