ignoreWorkspaceRootCheck: true
shamefullyHoist: true
strictPeerDependencies: false
sideEffectsCache: false
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - playground
catalogs:
  dev:
    '@antfu/eslint-config': ^7.7.3
    '@antfu/ni': ^29.0.0
    '@antfu/utils': ^9.3.0
    '@iconify/json': ^2.2.450
    '@playwright/test': ^1.58.2
    '@types/codemirror': ^5.60.17
    '@types/node': ^25.5.0
    '@unocss/eslint-config': ^66.6.6
    '@unocss/eslint-plugin': ^66.6.6
    '@vitejs/devtools': ^0.1.2
    '@vitejs/plugin-vue': ^6.0.5
    '@vue/compiler-sfc': ^3.5.30
    bumpp: ^11.0.1
    eslint: ^10.0.3
    lint-staged: ^16.4.0
    premove: ^4.0.0
    serve: ^14.2.6
    simple-git-hooks: ^2.13.1
    skills-npm: ^1.1.0
    typescript: ^5.9.3
    unbuild: ^3.6.1
    unocss: ^66.6.6
    unplugin-auto-import: ^21.0.0
    unplugin-vue-components: ^31.0.0
    vite: ^8.0.0
    vue-tsc: ^3.2.5
  frontend:
    '@vueuse/core': ^14.2.1
    '@vueuse/router': ^14.2.1
    codemirror: ^5.65.16
    codemirror-theme-vars: ^0.1.2
    comlink: ^4.4.2
    diff-match-patch-es: ^1.0.1
    echarts: ^6.0.0
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    ohash: ^2.0.11
    pathe: ^2.0.3
    perfect-debounce: ^2.1.0
    pinia: ^3.0.4
    splitpanes: ^4.0.4
    vis-data: ^8.0.3
    vis-network: ^10.0.2
    vue: ^3.5.30
    vue-echarts: ^8.0.1
    vue-router: ^5.0.3
  prod:
    '@nuxt/kit': ^4.4.2
    '@vitejs/devtools-kit': ^0.1.2
    ansis: ^4.2.0
    error-stack-parser-es: ^1.0.5
    obug: ^2.1.1
    open: ^11.0.0
    sirv: ^3.0.2
    unplugin-utils: ^0.3.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
