packages:
  - playground
catalogs:
  dev:
    '@antfu/eslint-config': ^4.14.1
    '@antfu/ni': ^25.0.0
    '@antfu/utils': ^9.2.0
    '@iconify/json': ^2.2.348
    '@types/codemirror': ^5.60.16
    '@types/debug': ^4.1.12
    '@types/node': ^22.15.31
    '@unocss/eslint-config': ^66.2.0
    '@unocss/eslint-plugin': ^66.2.0
    '@vitejs/plugin-vue': ^5.2.4
    '@vue/compiler-sfc': ^3.5.16
    bumpp: ^10.1.1
    eslint: ^9.29.0
    lint-staged: ^16.1.1
    rimraf: ^6.0.1
    serve: ^14.2.4
    simple-git-hooks: ^2.13.0
    typescript: ^5.8.3
    unbuild: ^3.5.0
    unocss: ^66.2.0
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.7.0
    unplugin-vue-router: ^0.12.0
    vite: npm:rolldown-vite@6.3.0-beta.5
    vue-tsc: ^2.2.10
  frontend:
    '@vueuse/core': ^13.3.0
    '@vueuse/router': ^13.3.0
    codemirror: ^5.65.16
    codemirror-theme-vars: ^0.1.2
    comlink: ^4.4.2
    diff-match-patch-es: ^1.0.1
    echarts: ^5.6.0
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    ohash: ^2.0.11
    pathe: ^2.0.3
    perfect-debounce: ^1.0.0
    pinia: ^3.0.3
    splitpanes: ^4.0.4
    vis-data: ^7.1.9
    vis-network: ^9.1.12
    vite-dev-rpc: ^1.0.7
    vite-hot-client: ^2.0.4
    vue: ^3.5.16
    vue-echarts: ^7.0.3
    vue-router: ^4.5.1
  prod:
    '@nuxt/kit': ^3.17.5
    ansis: ^3.17.0
    debug: ^4.4.1
    error-stack-parser-es: ^1.0.5
    open: ^10.1.2
    sirv: ^3.0.1
    unplugin-utils: ^0.2.4
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
