/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Badge: typeof import('./components/Badge.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    DiffEditor: typeof import('./components/DiffEditor.vue')['default']
    Graph: typeof import('./components/Graph.vue')['default']
    ModuleId: typeof import('./components/ModuleId.vue')['default']
    ModuleList: typeof import('./components/ModuleList.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    PluginChart: typeof import('./components/PluginChart.vue')['default']
    PluginName: typeof import('./components/PluginName.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./components/SearchBox.vue')['default']
    SegmentControl: typeof import('./components/SegmentControl.vue')['default']
  }
}
