/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./components/Badge.vue')['default']
    ByteSizeDisplay: typeof import('./components/ByteSizeDisplay.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    copy: typeof import('./components/WaterfallChart copy.vue')['default']
    DiffEditor: typeof import('./components/DiffEditor.vue')['default']
    DurationDisplay: typeof import('./components/DurationDisplay.vue')['default']
    ErrorDisplay: typeof import('./components/ErrorDisplay.vue')['default']
    FileIcon: typeof import('./components/FileIcon.vue')['default']
    FilepathItem: typeof import('./components/FilepathItem.vue')['default']
    Graph: typeof import('./components/Graph.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ModuleId: typeof import('./components/ModuleId.vue')['default']
    ModuleList: typeof import('./components/ModuleList.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NumberWithUnit: typeof import('./components/NumberWithUnit.vue')['default']
    PluginChart: typeof import('./components/PluginChart.vue')['default']
    PluginName: typeof import('./components/PluginName.vue')['default']
    QuerySelector: typeof import('./components/QuerySelector.vue')['default']
    RadioGroup: typeof import('./components/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./components/SearchBox.vue')['default']
    SegmentControl: typeof import('./components/SegmentControl.vue')['default']
    ServerChart: typeof import('./components/ServerChart.vue')['default']
    Waterfall: typeof import('./components/waterfall.vue')['default']
    WaterfallChart: typeof import('./components/WaterfallChart.vue')['default']
    WaterfallOverviewChart: typeof import('./components/WaterfallOverviewChart.vue')['default']
    WaterfallRangeChart: typeof import('./components/WaterfallRangeChart.vue')['default']
  }
}
