/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Badge: typeof import('./components/Badge.vue')['default']
    'Carbon:cloudServices': typeof import('~icons/carbon/cloud-services')['default']
    'Carbon:compare': typeof import('~icons/carbon/compare')['default']
    'Carbon:ibmWatsonDiscovery': typeof import('~icons/carbon/ibm-watson-discovery')['default']
    'Carbon:list': typeof import('~icons/carbon/list')['default']
    'Carbon:listBoxes': typeof import('~icons/carbon/list-boxes')['default']
    'Carbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    'Carbon:network4': typeof import('~icons/carbon/network4')['default']
    'Carbon:renew': typeof import('~icons/carbon/renew')['default']
    'Carbon:textWrap': typeof import('~icons/carbon/text-wrap')['default']
    'Carbon:timer': typeof import('~icons/carbon/timer')['default']
    CarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    CarbonArrowUpLeft: typeof import('~icons/carbon/arrow-up-left')['default']
    CarbonChevronLeft: typeof import('~icons/carbon/chevron-left')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSidePanelClose: typeof import('~icons/carbon/side-panel-close')['default']
    CarbonSidePanelOpen: typeof import('~icons/carbon/side-panel-open')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Container: typeof import('./components/Container.vue')['default']
    DiffEditor: typeof import('./components/DiffEditor.vue')['default']
    Graph: typeof import('./components/Graph.vue')['default']
    ModuleId: typeof import('./components/ModuleId.vue')['default']
    ModuleList: typeof import('./components/ModuleList.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    PluginChart: typeof import('./components/PluginChart.vue')['default']
    PluginName: typeof import('./components/PluginName.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./components/SearchBox.vue')['default']
    SegmentControl: typeof import('./components/SegmentControl.vue')['default']
    ServerChart: typeof import('./components/ServerChart.vue')['default']
  }
}
